/* File name: ryc-ar.js — shared Arabic UI dictionary. */
window.RYC_AR = {
  "Rest Your Case": "ريست يور كيس",
  "REST YOUR CASE /": "ريست يور كيس /",
  "Tactical Trial Simulator": "محاكاة المحاكمات",
  "Rest Your Case | Procedural Defense Simulator": "ريست يور كيس | محاكاة الدفاع الجنائي",
  "Rest Your Case | Rooms & Case Notebook": "ريست يور كيس | الغرف ودفتر القضية",
  "Rest Your Case | Legal Library": "ريست يور كيس | المكتبة القانونية",
  "Rest Your Case | Field Manual & Setup": "ريست يور كيس | دليل اللعب والإعداد",
  "Case Archive | Rest Your Case": "أرشيف القضايا | ريست يور كيس",
  "Overview": "الرئيسية",
  "Menu": "القائمة",
  "Key": "المفتاح",
  "Settings": "الإعدادات",
  "Close": "إغلاق",
  "Close ×": "إغلاق ×",
  "Close menu": "إغلاق القائمة",
  "Site navigation": "تصفح الموقع",
  "Case Shelf": "رف القضايا",
  "Case Files Shelf": "رف ملفات القضايا",
  "Case Archive": "أرشيف القضايا",
  "Case archive": "أرشيف القضايا",
  "Case collection": "مجموعة القضايا",
  "The records room": "غرفة السجلات",
  "The defense reference collection": "مجموعة مراجع الدفاع",
  "THE DEFENSE REFERENCE COLLECTION": "مجموعة مراجع الدفاع",
  "Legal Library": "المكتبة القانونية",
  "Legal library": "المكتبة القانونية",
  "Legal library ↗": "المكتبة القانونية ↗",
  "How to Play": "طريقة اللعب",
  "Setup Guide": "دليل الإعداد",
  "Setup & API Key": "الإعداد ومفتاح الخدمة",
  "Live Terminal": "غرفة المحاكمة",
  "Live rooms": "الغرف المباشرة",
  "Rooms": "الغرف",
  "Your rooms": "غرفك",
  "Notebook": "دفتر القضية",
  "Case notebook": "دفتر القضية",
  "Notebook Locked": "دفتر القضية مغلق",
  "Live Trial": "المحاكمة المباشرة",
  "Start Live Trial": "بدء محاكمة",
  "Case Intake Docket": "ملف استقبال القضية",
  "No active case": "لا توجد قضية نشطة",
  "No active case dossier pulled.": "لم يُفتح ملف قضية نشطة.",
  "Choose a case from the archive": "اختر قضية من الأرشيف",
  "Start a live trial from the Overview or Shelf to assign a case file.": "ابدأ محاكمة من الرئيسية أو رف القضايا لفتح ملف.",
  "Anatomy of a Trial": "مراحل المحاكمة",
  "Core Gameplay Loop": "خطوات اللعب الأساسية",
  "Probe Your Client": "استجوب موكلك",
  "Manage Action Points (AP)": "إدارة نقاط الإجراءات [AP]",
  "Dismantle the State's Case": "اختبر أدلة الادعاء",
  "Win & Decode Truth": "النتيجة وكشف الحقيقة",
  "Trial Rules": "قواعد الصعوبة",
  "Difficulty": "الصعوبة",
  "Trial Difficulty:": "صعوبة المحاكمة:",
  "Complexity": "تعقيد القضية",
  "Case Complexity:": "تعقيد القضية:",
  "Level 3": "المستوى 3",
  "Lvl 3": "المستوى 3",
  "Charge Genre": "نوع الجريمة",
  "Case type": "نوع القضية",
  "Random Genre": "نوع عشوائي",
  "Violent Felony": "جنايات العنف",
  "White-Collar Fraud": "الجرائم المالية والاحتيال",
  "Cybercrime": "الجرائم الرقمية",
  "Substance / Narcotics": "المخدرات والمواد المراقبة",
  "Overcharge": "تهم مبالغ فيها وقتل بظروف مخففة",
  "Sandbox": "وضع الاستكشاف",
  "Easy": "سهل",
  "Normal": "عادي",
  "Hard": "صعب",
  "Sandbox (Unlimited AP)": "وضع الاستكشاف (نقاط غير محدودة)",
  "Easy (150% case AP)": "سهل (150% من نقاط القضية)",
  "Normal (100% case AP)": "عادي (100% من نقاط القضية)",
  "Hard (75% case AP)": "صعب (75% من نقاط القضية)",
  "Unlimited": "غير محدود",
  "AP": "نقاط الإجراءات",
  "Action Points (AP)": "نقاط الإجراءات [AP]",
  "Turn": "الجولة",
  "Strikes": "المخالفات",
  "Judicial Strikes (0/3)": "مخالفات المحكمة (0/3)",
  "Trial resources": "موارد المحاكمة",
  "Engine": "المحرك",
  "Engine:": "المحرك:",
  "Smart": "ذكي",
  "Light": "خفيف",
  "Smart:": "الذكي:",
  "Light:": "الخفيف:",
  "Smarter responses, but more expensive.": "ردود أذكى بتكلفة أعلى.",
  "Less smart, but faster and cheaper.": "أقل ذكاءً، لكنه أسرع وأقل تكلفة.",
  "Choose your engine and optional API key.": "اختر المحرك وأضف مفتاح الخدمة إن أردت.",
  "Bring Your Own Key (BYOK)": "استخدام مفتاحك الخاص [BYOK]",
  "Google AI Studio Key": "مفتاح Google AI Studio",
  "Get a Free Key ↗": "احصل على مفتاح مجاني ↗",
  "Save Settings": "حفظ الإعدادات",
  "Use System Key": "استخدام مفتاح النظام",
  "Show key": "إظهار المفتاح",
  "Save": "حفظ",
  "Cancel": "إلغاء",
  "Understood": "فهمت",
  "Try Again": "إعادة المحاولة",
  "Plug In Your Key": "أضف مفتاحك",
  "Find Case": "البحث عن قضية",
  "Find a case": "البحث عن قضية",
  "Find Another": "البحث عن قضية أخرى",
  "Accept Retainer": "قبول القضية",
  "Accept case →": "قبول القضية ←",
  "Begin trial →": "بدء المحاكمة ←",
  "Take this case?": "هل تريد تولي هذه القضية؟",
  "Keep reviewing": "متابعة المراجعة",
  "Case brief": "ملخص القضية",
  "The allegation": "رواية الاتهام",
  "Police Allegation": "رواية الشرطة",
  "Charge:": "التهمة:",
  "Charge": "التهمة",
  "Client:": "الموكل:",
  "Client": "الموكل",
  "Defendant": "المتهم",
  "Judge:": "القاضي:",
  "Judge": "القاضي",
  "Prosecutor:": "المدعي:",
  "Prosecutor": "ممثل الادعاء",
  "Occupation:": "المهنة:",
  "Occupation": "المهنة",
  "Civilian": "مدني",
  "Police officer": "ضابط شرطة",
  "Expert": "خبير",
  "Not yet classified": "لم تُحدد بعد",
  "Starter Exhibits:": "المعروضات الأولية:",
  "Initial exhibits": "المعروضات الأولية",
  "Initial evidence": "الأدلة الأولية",
  "Evidence": "الأدلة",
  "Evidence Docket": "سجل المعروضات",
  "Evidence docket": "سجل المعروضات",
  "Discovery preview": "معاينة الأدلة المتاحة",
  "Discovery": "الكشف عن الأدلة [Discovery]",
  "Marked": "مرقّم فقط [Marked]",
  "Admitted": "مقبول كدليل [Admitted]",
  "Suppressed": "مستبعد [Suppressed]",
  "SUPPRESSED": "مستبعد [Suppressed]",
  "Physical": "مادي",
  "Documentary": "مستندي",
  "Digital": "رقمي",
  "Forensic": "جنائي مخبري",
  "Exhibit": "معروض",
  "Ex. 1 (Tag)": "المعروض 1 (الرقم)",
  "Ex. 1 Glove, Ex. 2 CAD Log": "المعروض 1: قفاز، المعروض 2: سجل بلاغات",
  "Forensic Notes...": "ملاحظات الفحص الجنائي...",
  "Log Discovery Exhibit": "تسجيل معروض جديد",
  "+ Manual Entry": "+ إضافة يدوية",
  "Logging Discovery:": "تسجيل الأدلة:",
  "Status Toggles:": "تغيير حالة المعروض:",
  "Case resolution": "نتيجة القضية",
  "Active Court Record": "سجل المحكمة النشط",
  "Defense Archive": "أرشيف الدفاع",
  "Attorney General Theories": "أفكار الدفاع العامة",
  "*Private notes. The Court does not recognize unproven defense theories until introduced via testimony or admitted exhibits.": "*ملاحظات خاصة. لا تُعامل أفكارك كأدلة أمام المحكمة حتى تدعمها شهادة أو معروض مقبول.",
  "Case 1 of 1": "القضية 1 من 1",
  "Case Files": "ملفات القضايا",
  "All files": "جميع الملفات",
  "Filed": "مؤرشفة",
  "Intake": "استقبال",
  "Pending intake": "بانتظار الاستقبال",
  "All case types": "جميع أنواع القضايا",
  "All difficulties": "جميع مستويات الصعوبة",
  "File collection": "مجموعة الملفات",
  "File order": "ترتيب الملفات",
  "Newest first": "الأحدث أولاً",
  "Oldest first": "الأقدم أولاً",
  "Title A–Z": "ترتيب العنوان",
  "Title": "العنوان",
  "Search": "بحث",
  "Search the files": "البحث في الملفات",
  "Search every chapter": "البحث في كل الأقسام",
  "Search the collection": "البحث في المجموعة",
  "Search the legal library": "البحث في المكتبة القانونية",
  "Case title, client, or charge": "عنوان القضية أو الموكل أو التهمة",
  "Clear filters": "مسح عوامل التصفية",
  "Opening the archive…": "جارٍ فتح الأرشيف…",
  "Saved case folders": "ملفات القضايا المحفوظة",
  "Skip to case files": "الانتقال إلى ملفات القضايا",
  "Skip to library": "الانتقال إلى المكتبة",
  "Return to overview": "العودة للرئيسية",
  "← Archive": "الأرشيف →",
  "Resume trial": "استئناف المحاكمة",
  "Current trial": "المحاكمة الحالية",
  "Finish case setup": "إكمال إعداد القضية",
  "Finish setup": "إكمال الإعداد",
  "Retry setup": "إعادة محاولة الإعداد",
  "Retry action": "إعادة محاولة الإجراء",
  "In progress": "قيد التنفيذ",
  "Case setup incomplete": "إعداد القضية غير مكتمل",
  "Intake has not initialized": "لم تبدأ مرحلة الاستقبال",
  "Purge case": "حذف القضية",
  "Purge current case": "حذف القضية الحالية",
  "Purge current case?": "حذف القضية الحالية؟",
  "Purge Data": "حذف البيانات",
  "Wipe Trial Data?": "حذف بيانات المحاكمة؟",
  "Type CONFIRM": "اكتب CONFIRM",
  "Type CONFIRM to purge": "اكتب CONFIRM للحذف",
  "This cannot be undone.": "لا يمكن التراجع عن هذا الإجراء.",
  "This will permanently delete your active case file.": "سيُحذف ملف قضيتك الحالية نهائياً.",
  "Wiping Data:": "حذف البيانات:",
  "THE FIELD MANUAL": "دليل اللعب",
  "Field Manual: How to Play": "دليل طريقة اللعب",
  "Open the manual ↓": "افتح الدليل ↓",
  "1. The Game Cycle": "1. مراحل اللعب",
  "2. Rooms & Conversations": "2. الغرف والمحادثات",
  "3. Resource Economics": "3. موارد القضية",
  "4. Command Line Syntax": "4. الأوامر النصية",
  "5. Your Legal Team": "5. فريقك القانوني",
  "6. Case Management": "6. إدارة القضية",
  "Phase 1 (Intake):": "المرحلة 1 (استقبال الموكل):",
  "Phase 2 (Pre-Trial):": "المرحلة 2 (قبل المحاكمة):",
  "Phase 3 (Trial):": "المرحلة 3 (المحاكمة):",
  "Phase 4 (Verdict):": "المرحلة 4 (النتيجة):",
  "Phase 1: Intake": "المرحلة 1: استقبال الموكل",
  "Phase 2: Investigation": "المرحلة 2: التحقيق",
  "Phase 2.5: Pre-Trial Motions & Conferences": "المرحلة 2.5: الطلبات والجلسات التمهيدية",
  "Phase 3: Trial": "المرحلة 3: المحاكمة",
  "Phase 3.5: Defense Case-in-Chief": "المرحلة 3.5: عرض أدلة الدفاع",
  "Phase 4: Closing Arguments & Verdict": "المرحلة 4: المرافعات والنتيجة",
  "Manual Integration": "الاستخدام اليدوي",
  "Offline / Standalone Prompts": "تعليمات اللعب في واجهة خارجية",
  "Desktop:": "على الحاسوب:",
  "Mobile:": "على الهاتف:",
  "The": "الـ",
  "and": "و",
  "or": "أو",
  "to begin.": "للبدء.",
  "start a new intake": "ابدأ استقبال قضية جديدة",
  "tab is your private workspace.": "مساحة عمل خاصة بك.",
  "Active": "نشط",
  "Address witness": "مخاطبة الشاهد",
  "Another known witness’s name": "اسم شاهد آخر معروف في القضية",
  "Known witnesses": "الشهود المعروفون",
  "Select a known witness": "اختر شاهداً معروفاً",
  "Speak to a witness": "مخاطبة شاهد",
  "Speak to:": "تحدث إلى:",
  "Witness": "الشاهد",
  "Witness selection": "اختيار الشاهد",
  "Your client": "موكلك",
  "Your office": "مكتبك",
  "Courtroom": "قاعة المحكمة",
  "DA’s office": "مكتب الادعاء",
  "Senior partner": "الشريك الأقدم",
  "Partner": "الشريك",
  "Diaz": "دياز",
  "Investigator Diaz": "المحقق دياز",
  "Client interview": "مقابلة الموكل",
  "Client intake": "استقبال الموكل",
  "Client interview room": "غرفة مقابلة الموكل",
  "Client conversation": "محادثة الموكل",
  "Court and case conversation": "محادثة المحكمة والقضية",
  "Senior partner conversation": "محادثة الشريك الأقدم",
  "Investigator conversation": "محادثة المحقق",
  "Conversation": "المحادثة",
  "CURRENT CONVERSATION": "المحادثة الحالية",
  "CASE DOCUMENTS": "وثائق القضية",
  "History": "السجل",
  "Object": "اعتراض",
  "Send": "إرسال",
  "Message to selected recipient": "رسالة إلى الشخص المحدد",
  "Private assistant message": "رسالة خاصة للمساعد",
  "Ask a question or make your next move…": "اطرح سؤالاً أو اتخذ خطوتك التالية…",
  "Ask for tactical advice…": "اطلب نصيحة لخطة الدفاع…",
  "Prepare your questions before entering court.": "جهّز أسئلتك قبل دخول المحكمة.",
  "Choose a room": "اختر غرفة",
  "Room navigation": "التنقل بين الغرف",
  "Room actions": "إجراءات الغرفة",
  "Illustrated room": "الغرفة المصورة",
  "Room artwork unavailable. All room actions are available below.": "تعذر تحميل صورة الغرفة. جميع إجراءاتها متاحة أدناه.",
  "Close document": "إغلاق الوثيقة",
  "Return to room": "العودة للغرفة",
  "Back to room ×": "العودة للغرفة ×",
  "Back to shelf ×": "العودة للرف ×",
  "Case document": "وثيقة القضية",
  "Commencing Court Proceedings": "جارٍ بدء المحاكمة",
  "Inv. Diaz is pulling docket filings & discovery...": "يبحث المحقق دياز في الملفات والأدلة...",
  "Waiting for a reply… 0s / 60s": "انتظار الرد… 0 ث / 60 ث",
  "Consult Partner": "استشارة الشريك",
  "Failed to pull case file.": "تعذر جلب ملف القضية.",
  "Judicial Record Notice": "تنبيه بشأن سجل المحكمة",
  "Murder 1st": "قتل من الدرجة الأولى",
  "FRE 404(b): Propensity": "استخدام الشخصية لاستنتاج الذنب [Propensity] — FRE 404(b)",
  "FRE 611(c): Leading on Direct": "سؤال موحٍ في الاستجواب المباشر [Leading] — FRE 611(c)",
  "FRE 611: Compound / Assumes Facts": "سؤال مركب أو يفترض وقائع [Compound / Assumes Facts] — FRE 611",
  "FRE 701: Lay Opinion": "رأي شاهد عادي [Lay Opinion] — FRE 701",
  "FRE 802: Hearsay": "شهادة سماعية [Hearsay] — FRE 802",
  "About this collection": "عن هذه المجموعة",
  "Browse all chapters": "تصفح جميع الأقسام",
  "Browse by topic": "التصفح حسب الموضوع",
  "Build your defense": "ابنِ دفاعك",
  "Building a closing argument": "بناء المرافعة الختامية [Closing Argument]",
  "Contents": "المحتويات",
  "Library contents": "محتويات المكتبة",
  "LEGAL REFERENCE": "المرجع القانوني",
  "Legal reference book": "كتاب المرجع القانوني",
  "Illustrated reference workspace": "مساحة المراجع المصورة",
  "All topics": "جميع المواضيع",
  "Start here": "ابدأ هنا",
  "Courtroom objections": "اعتراضات المحكمة [Objections]",
  "Charges & what must be proved": "التهم وما يجب إثباته",
  "Police actions & evidence challenges": "إجراءات الشرطة واختبار الأدلة",
  "Witness credibility": "مصداقية الشهود [Credibility]",
  "Prosecution tactics to recognize": "أساليب الادعاء التي ينبغي ملاحظتها",
  "Investigation & action points": "التحقيق ونقاط الإجراءات [AP]",
  "Reading exhibits critically": "قراءة المعروضات بعناية",
  "Courtroom field guide": "دليل شخصيات المحكمة",
  "01. Start here": "01. ابدأ هنا",
  "02. Courtroom objections": "02. اعتراضات المحكمة",
  "03. Charges & what must be proved": "03. التهم وما يجب إثباته",
  "04. Police actions & evidence challenges": "04. إجراءات الشرطة واختبار الأدلة",
  "05. Witness credibility": "05. مصداقية الشهود",
  "06. Prosecution tactics to recognize": "06. أساليب الادعاء",
  "07. Investigation & action points": "07. التحقيق ونقاط الإجراءات",
  "08. Reading exhibits critically": "08. قراءة المعروضات بعناية",
  "09. Building a closing argument": "09. بناء المرافعة الختامية",
  "10. Courtroom field guide": "10. دليل شخصيات المحكمة",
  "Nine library chapters": "تسعة أقسام للمكتبة",
  "Nine chapters · Tap anywhere inside a chapter’s shelf section.": "تسعة أقسام · اضغط على مساحة القسم داخل الرف لفتحه.",
  "Wooden legal bookshelf with a central shelf arranged in five rows and two columns": "رف كتب قانونية خشبي بأقسام مرتبة في خمسة صفوف وعمودين",
  "Show examples": "إظهار الأمثلة",
  "Hide examples": "إخفاء الأمثلة",
  "No matching entries": "لا توجد نتائج مطابقة",
  "Hearsay, DNA, self-defense…": "شهادة سماعية، DNA، دفاع عن النفس…",
  "Try hearsay, self-defense, DNA, or wire fraud": "جرّب: شهادة سماعية، دفاع عن النفس، DNA، أو احتيال إلكتروني",
  "Try a broader phrase or clear the filters to browse the full collection.": "جرّب عبارة أوسع أو امسح عوامل التصفية لعرض المجموعة كاملة.",
  "Brady: favorable evidence": "أدلة تساعد الدفاع [Brady]",
  "Giglio: witness benefits": "منافع الشهود [Giglio]",
  "Concealed witness deal": "اتفاق مخفي مع شاهد",
  "Crawford: confronting testimonial accusations": "حق مواجهة صاحب الاتهام [Crawford]",
  "Rule 702: expert testimony": "شهادة الخبير [Expert Testimony] — القاعدة 702",
  "Rule 901: authentication": "التحقق من أصالة الدليل [Authentication] — القاعدة 901",
  "Federal Rules of Evidence — U.S. Courts": "قواعد الإثبات الفدرالية [Federal Rules of Evidence] — المحاكم الأمريكية",
  "Shabani: no separate overt-act requirement under § 846": "قرار شاباني: لا يلزم فعل ظاهر مستقل [Overt Act] وفق المادة 846",
  "Reference reading for the evidence and disclosure explanations:": "مراجع شروح الأدلة والكشف عنها:",
  "The basic ideas behind every defense, explained without legal training.": "أفكار الدفاع الأساسية بشرح لا يتطلب دراسة القانون.",
  "Recognize the problem, state the ground, and ask for a focused ruling.": "حدّد المشكلة واذكر سببك واطلب قراراً واضحاً.",
  "Every charge in the case data, grouped by case type. These are RUC summaries; exact legal elements depend on the governing law.": "تهم اللعبة مرتبة حسب النوع. هذه ملخصات للعب؛ المتطلبات الدقيقة تتبع القانون الأمريكي المطبق على القضية.",
  "All eight legal flaws in the case data, translated into practical defense questions.": "المشكلات القانونية الثماني في بيانات اللعبة، على شكل أسئلة عملية للدفاع.",
  "All witness frictions and client complications: evaluate facts without turning suspicion into proof.": "مشكلات الشهود والموكلين: اختبر الوقائع دون تحويل الشك إلى إثبات.",
  "All five courtroom traps in the case data, with a clear response.": "أساليب الادعاء الخمسة في بيانات اللعبة، مع طريقة واضحة للرد.",
  "All eight investigation types. The AP figures come from the RUC data; findings still need context and a proper foundation.": "أنواع التحقيق الثمانية وكلفتها في اللعبة. نتائج التحقيق تحتاج سياقاً وأساساً مناسباً لقبولها كدليل.",
  "Every evidence anchor in the case data: what it may help prove and what to check.": "كل معروض في بيانات اللعبة: ما قد يثبته وما ينبغي فحصه.",
  "All five verdict guides. A weakness may defeat a greater charge while leaving a lesser offense for consideration.": "خمسة أدلة للمرافعة. قد يضعف الدليل تهمة أشد مع بقاء تهمة أخف محتملة.",
  "The fictional judges and prosecutors in RUC. These profiles guide gameplay; they do not change the legal rules.": "القضاة والمدعون الخياليون في اللعبة. صفاتهم ترشدك في اللعب ولا تغير القواعد القانونية.",
  "All explanations and examples are available below. Enable JavaScript to search, filter, and toggle examples.": "الشروح والأمثلة أدناه. فعّل JavaScript للبحث والتصفية وإظهار الأمثلة.",
  "Understand the rule. Know what to look for. Build your defense. Browse plain-English guides to the charges, evidence, and courtroom decisions you will encounter in Rest Your Case.": "افهم القاعدة واعرف ما تبحث عنه وابنِ دفاعك. شروح بسيطة للتهم والأدلة وقرارات المحكمة في ريست يور كيس. القانون المستخدم أمريكي فقط.",
  "This collection explains the legal concepts used in RUC's fictional U.S. courtroom. Charge summaries and character profiles reflect the game. Real statutes, evidence rules, and defenses vary by jurisdiction. Case names below refer to court decisions; FRE means Federal Rules of Evidence.": "تشرح المجموعة مفاهيم المحكمة الأمريكية الخيالية في اللعبة. ملخصات التهم والشخصيات تخص اللعب، والتفاصيل القانونية تختلف حسب المحكمة والقانون المطبق. أسماء القضايا أدناه لقرارات قضائية، وFRE تعني قواعد الإثبات الفدرالية [Federal Rules of Evidence]. العربية لغة عرض فقط وليست تغييراً للنظام القانوني.",
  "Choose a section. Find the argument you need.": "اختر قسماً واعثر على الحجة التي تحتاجها.",
  "A case begins with a closer look. Open a folder, review the brief, then decide which case to take.": "افتح ملفاً واقرأ ملخصه، ثم قرر أي قضية تتولى.",
  "Calibrate criteria and review prospective dossiers.": "اختر المعايير وراجع ملفات القضايا المعروضة.",
  "A fair-play procedural defense mystery engine powered by Google Gemini. Sift through tainted evidence, preserve constitutional protections, command your private investigator, and dismantle the prosecution's theory before jury deliberations.": "لعبة لغز ودفاع جنائي مدعومة بـ Google Gemini. افحص الأدلة، واحمِ حقوق موكلك، ووجّه محققك، واختبر رواية الادعاء قبل قرار المحلفين.",
  "You have limited turns to interview your client in holding. Ask precise questions to lock down their alibi. If you don't find the holes in their story, the DA will.": "اسأل موكلك بدقة عن مكانه وتوقيت الأحداث. اكتشف الثغرات في روايته قبل أن يستغلها الادعاء.",
  "In Phase 1, interview the defendant in holding. Ask direct questions to lock down their story before the DA attacks it. Trust nothing.": "في المرحلة الأولى، قابل موكلك واسأله بوضوح لتثبيت روايته، وتحقق من أقواله قبل مواجهتها بالادعاء.",
  "During investigation and trial, spend AP strategically with Investigator Diaz to subpoena records, run background checks, or file motions to suppress.": "أثناء التحقيق والمحاكمة، استخدم نقاطك مع المحقق دياز لطلب السجلات والتحقق من المعلومات وتقديم طلب استبعاد دليل [Motion to Suppress].",
  "In Phase 3, interrupt improper questions with Objections and confront hostile state witnesses with conflicting physical exhibits.": "في المرحلة الثالثة، اعترض على الأسئلة غير المناسبة وواجه شهود الادعاء بمعروضات تناقض أقوالهم.",
  "Deliver your closing argument. After the verdict, the hidden Truth Hash evaluates your performance and reveals the actual timeline.": "قدّم مرافعتك الختامية. بعد الحكم تُكشف الحقيقة المحفوظة وتسلسل الأحداث الفعلي.",
  "Deliver a closing argument. The jury renders a verdict, and the hidden Truth Hash evaluates your performance and reveals the actual timeline.": "قدّم مرافعتك الختامية، ثم يصدر المحلفون النتيجة وتُكشف حقيقة الأحداث المحفوظة.",
  "Direct Investigator Diaz to scout court filings and police dispatch logs matching your criteria.": "وجّه المحقق دياز للبحث في ملفات المحكمة وسجلات البلاغات حسب معاييرك.",
  "Direct Investigator Diaz. This is where you spend AP to subpoena bank records, trace IP logs, or file motions to suppress tainted discovery.": "وجّه دياز واستخدم نقاط الإجراءات لطلب سجلات مصرفية أو رقمية أو لتقديم طلب استبعاد دليل.",
  "Cross-examine State witnesses. Use the `!` menu to object to improper DA questions in real-time. Introduce admitted exhibits to impeach lying witnesses.": "استجوب شهود الادعاء واستخدم قائمة الاعتراضات للأسئلة غير المناسبة. اعرض الأدلة المقبولة لاختبار مصداقيتهم.",
  "AP represents your firm's time and budget. Issuing subpoenas, ordering forensic analysis, and filing formal motions cost AP. General conversation with your client or Partner is free. AP carries through every phase. Normal budgets for complexity 1–5 are 6, 8, 10, 12 and 14 AP; Easy receives 150% and Hard 75%, rounded up. Sandbox displays Unlimited while tracking 1,000,000 AP internally. New trial leads can award 2 AP once per development; replaying an existing lead earns nothing.": "تمثل نقاط الإجراءات [AP] وقت مكتبك وميزانيته. طلب السجلات والفحص الجنائي والطلبات الرسمية يستهلك نقاطاً، أما الحديث العادي والاستشارة فمجانيان. تنتقل النقاط بين المراحل. لمستويات التعقيد 1–5 يحصل العادي على 6 و8 و10 و12 و14 نقطة، والسهل على 150% والصعب على 75% مع التقريب للأعلى. وضع الاستكشاف يعرض «غير محدود» ويبدأ بمليون نقطة داخلياً. قد يمنح تطور جديد في المحاكمة نقطتين مرة واحدة، ولا تُكافأ إعادة التحقيق في الخيط نفسه.",
  "The Judge tracks your conduct. Making frivolous arguments, pursuing badgering lines of questioning, or having your objections repeatedly overruled earns strikes. Max strikes = Mistrial/Contempt.": "يتابع القاضي سلوكك. التصرفات والمجادلات غير المناسبة قد ترفع عداد المخالفات في اللعبة. بلوغ الحد يؤثر على استمرار المحاكمة؛ هذا عداد للعب وليس قاعدة قانونية أمريكية فعلية.",
  "Choose a recipient before sending. History shows earlier conversation. Case brief, evidence, and notebook buttons remain available regardless of which objects are visible in the scene.": "اختر الشخص قبل الإرسال. يعرض السجل المحادثة السابقة، وتبقى أزرار الملخص والأدلة والدفتر متاحة مهما ظهر في الصورة.",
  "The scene shows your current room and the conversation stays alongside it or below it.": "تظهر غرفتك الحالية وتبقى المحادثة بجانبها أو أسفلها.",
  "Use the room bar on wider screens or the three-dot room menu on phones. Choose a recipient to address the judge, witness, client, or prosecutor. Visit Diaz for investigation and your senior partner for private strategy advice. Changing rooms costs nothing and sends no message.": "استخدم شريط الغرف على الشاشة الكبيرة أو قائمة النقاط الثلاث على الهاتف. اختر القاضي أو الشاهد أو الموكل أو المدعي. زر دياز للتحقيق والشريك للاستشارة الخاصة. التنقل مجاني ولا يرسل رسالة.",
  "Use the room bar to move between offices and court. The scene and dialogue appear side by side.": "تنقل عبر شريط الغرف؛ تظهر الغرفة والمحادثة جنباً إلى جنب.",
  "Use the three-dot room menu. The scene sits above dialogue; opening the keyboard reduces the scene to leave writing space.": "افتح قائمة النقاط الثلاث. تظهر الغرفة فوق المحادثة وتصغر عند فتح لوحة المفاتيح لتترك مساحة للكتابة.",
  "Open documents from a room object or its labeled button. Long records scroll at a readable size. History reveals earlier dialogue. Your office contains the case folder, notebook, and defense board; the library’s nine shelf sections open the reference collection.": "افتح الوثائق من عناصر الغرفة أو أزرارها. مرّر السجلات الطويلة واعرض المحادثة السابقة من «السجل». يحوي مكتبك الملف والدفتر ولوحة الدفاع؛ وتفتح أقسام رف المكتبة المراجع.",
  "Visit the Senior Partner’s office for private strategy advice, or Diaz’s room for investigation. Each keeps its own conversation history.": "زر مكتب الشريك للاستشارة الخاصة أو غرفة دياز للتحقيق. لكل منهما سجل محادثة مستقل.",
  "Strategy consultations cost 0 AP. Investigative actions follow the existing AP rules; changing rooms costs nothing. Use the advice notes and report buttons to review their recorded responses.": "الاستشارة مجانية، والتحقيق يتبع كلفة نقاط الإجراءات. التنقل مجاني. راجع الردود السابقة من أزرار النصائح والتقارير.",
  "While you primarily use natural language to talk, system directives use slashes:": "يمكنك الحديث بلغة عادية، أما أوامر النظام فتبدأ بعلامة / وتبقى بالإنجليزية:",
  "- Demands granular forensic data or chain of custody on a marked exhibit.": "- يطلب تفاصيل الفحص أو سلسلة حيازة معروض مرقّم.",
  "- Spends AP to legally compel phone records, bank statements, or server logs.": "- يستخدم نقاطاً لطلب سجلات هواتف أو بنوك أو خوادم وفق الإجراءات.",
  "- Summarizes the trial so far (useful if you hit context limits).": "- يلخص ما جرى في المحاكمة.",
  "If the AI mentions a piece of evidence, manually log it via `+ Manual Entry`.": "إذا ذُكر دليل ولم يظهر في السجل، أضفه عبر «+ إضافة يدوية».",
  "Cycle evidence status between Marked, Admitted, or Suppressed.": "بدّل عرض الحالة بين مرقّم [Marked] ومقبول [Admitted] ومستبعد [Suppressed] بحسب سجل المحكمة.",
  "Draft general cross-examinations or connect contradictions here. Specific exhibit notes can be attached directly to the exhibit card above.": "اكتب أسئلة الاستجواب أو اربط التناقضات هنا. يمكنك وضع ملاحظة خاصة بكل معروض على بطاقته.",
  "This removes the active trial, its notes and conversations. Your archived files and API key stay available.": "يحذف المحاكمة النشطة وملاحظاتها ومحادثاتها. تبقى القضايا المؤرشفة ومفتاح الخدمة.",
  "To start a fresh trial, click `Delete Case` (located in the Terminal header or Notebook) and type `CONFIRM` to wipe local storage.": "لبدء محاكمة جديدة، اختر حذف القضية واكتب CONFIRM لحذف بيانات المحاكمة الحالية.",
  "Trashing this fact only removes it from your active desk view. It remains established in the judicial record and can still be cited by the Prosecution or Judge.": "نقل الواقعة للأرشيف يخفيها من مكتبك فقط. تبقى في سجل المحكمة وقد يستند إليها القاضي أو الادعاء.",
  "You will begin with client intake. The case will move from this collection into your current trial.": "تبدأ باستقبال الموكل، وينتقل الملف من المجموعة إلى المحاكمة الحالية.",
  "Review what is in the file. Listing an exhibit here does not make it admitted evidence.": "راجع محتويات الملف. ظهور معروض هنا لا يعني قبوله كدليل أمام المحكمة.",
  "Reviewing a file uses no action points. Accepting it starts a new trial.": "مراجعة الملف مجانية. قبوله يبدأ محاكمة جديدة.",
  "This intake has not started yet.": "لم تبدأ مرحلة الاستقبال بعد.",
  "Enable JavaScript to read the saved case files in this browser.": "فعّل JavaScript لقراءة القضايا المحفوظة في هذا المتصفح.",
  "Open the archive": "افتح الأرشيف",
  "Bypass public rate limits. Plug in your free Google AI Studio key to play indefinitely.": "أضف مفتاح Google AI Studio الخاص بك لاستخدام حصته بدلاً من المفتاح العام. يبقى الاستخدام تابعاً لحدود الخدمة.",
  "🔒 Your key is stored strictly in your browser's local storage. It is never saved to an external database.": "🔒 يُحفظ مفتاحك في هذا المتصفح، ولا يُحفظ في قاعدة بيانات خارجية.",
  "Complete operational directives for the Rest Your Case tactical engine.": "تعليمات تشغيل محرك ريست يور كيس.",
  "If you are running the scenario directly in an external LLM interface (Claude Projects, ChatGPT Custom GPTs, or AI Studio web), initialize with the standard": "إذا لعبت مباشرة في واجهة ذكاء اصطناعي خارجية، مثل Claude أو ChatGPT أو AI Studio، فابدأ بالأمر المعتاد",
  "directive and adhere to the strict turn protocol outlined in the Field Manual above.": "والتزم بنظام الجولات الموضح في الدليل أعلاه.",
  "Directives for native ChatGPT/Claude play coming soon.": "ستتوفر تعليمات اللعب المباشر في ChatGPT وClaude لاحقاً.",
  "Auto-sync": "حفظ تلقائي",
  "Dossier pages": "صفحات الملف",
  "The court": "المحكمة",
  "The State claims the defendant was found near the scene.": "يدّعي الادعاء أن المتهم وُجد قرب موقع الحادث.",
  "Procedural Engine © 2026": "محرك المحاكمة © 2026",
  "Rest Your Case © 2026. Local-First Client Storage.": "ريست يور كيس © 2026. تُحفظ بياناتك في هذا المتصفح.",
  "Rest Your Case · Files saved in this browser": "ريست يور كيس · الملفات محفوظة في هذا المتصفح",
  "🗄️ Case Shelf": "🗄️ رف القضايا",
  "⚖️ TIP: Every major move costs Action Points (AP). Plan carefully. | ⚖️ TIP: Review case dossiers in Intake or pull archived files from your Shelf. | ⚖️ TIP: Consult your Senior Partner (/consult) or Investigator Diaz without spending AP.": "⚖️ تلميح: خطط لاستخدام نقاط الإجراءات. | ⚖️ تلميح: راجع الملفات من الاستقبال أو الرف. | ⚖️ تلميح: الاستشارة مع الشريك أو دياز مجانية.",
  "⚖️ TIP: Every major move costs Action Points (AP). Plan carefully. | ⚖️ TIP: You cannot Admit an exhibit without laying a foundation first. | ⚖️ TIP: Use /inspect on marked exhibits to uncover hidden details. | ⚖️ TIP: Consult your Senior Partner or Investigator Diaz without spending AP.": "⚖️ تلميح: خطط لاستخدام النقاط. | ⚖️ تلميح: أسّس المعروض قبل طلب قبوله. | ⚖️ تلميح: استخدم /inspect لفحص التفاصيل. | ⚖️ تلميح: الاستشارة مجانية.",
  "+ Manual entry": "+ إضافة يدوية",
  "Action not completed": "لم يكتمل الإجراء",
  "Active case": "قضية نشطة",
  "Address the bench, examine a witness, or challenge the prosecution.": "خاطب القاضي أو استجوب شاهداً أو اختبر حجة الادعاء.",
  "Advice notes": "ملاحظات الاستشارة",
  "Ask Diaz": "اسأل دياز",
  "Ask Diaz to check a lead…": "اطلب من دياز فحص خيط تحقيق…",
  "Ask Diaz to examine a lead or review the known evidence.": "اطلب من دياز فحص خيط أو مراجعة الأدلة المعروفة.",
  "Ask for legal strategy advice…": "اطلب نصيحة لخطة الدفاع…",
  "Case board": "لوحة القضية",
  "Case conversation": "محادثة القضية",
  "Case file": "ملف القضية",
  "Case folder": "مجلد القضية",
  "Case preparation": "التحضير للقضية",
  "Cases you save from the overview will be filed here, ready for a closer look.": "تظهر هنا القضايا التي تحفظها من الرئيسية لتراجعها لاحقاً.",
  "Choose a case to begin your defense.": "اختر قضية لبدء الدفاع.",
  "Choose anyone from either side, or enter another known witness’s name.": "اختر شاهداً من أي طرف أو اكتب اسم شاهد آخر معروف.",
  "Client occupation": "مهنة الموكل",
  "Client statement": "إفادة الموكل",
  "Clues board": "لوحة خيوط التحقيق",
  "Closing & courtroom guide": "المرافعة ودليل المحكمة",
  "Court is deliberating": "تنتظر المحكمة الرد",
  "Court record": "سجل المحكمة",
  "Courtroom behavior": "السلوك في المحكمة",
  "Current dialogue": "المحادثة الحالية",
  "Current phase": "المرحلة الحالية",
  "DA overview": "معلومات المدعي",
  "DEFENSE COUNSEL": "محامي الدفاع",
  "Defense counsel": "محامي الدفاع",
  "SENIOR PARTNER": "الشريك الأقدم",
  "THE BENCH / RECORD": "المحكمة / السجل",
  "Defense Annotations...": "ملاحظات الدفاع...",
  "Defense board": "لوحة الدفاع",
  "Defense preparation notes": "ملاحظات إعداد الدفاع",
  "Diaz investigating": "دياز يحقق",
  "Discuss an offer or request disclosure from the prosecutor.": "ناقش عرضاً أو اطلب كشف معلومات من الادعاء.",
  "Enter a name between 1 and 100 characters.": "اكتب اسماً من 1 إلى 100 حرف.",
  "Enter a witness’s name from your case to address them.": "اكتب اسم شاهد من قضيتك لمخاطبته.",
  "Established facts": "الوقائع المثبتة",
  "Established facts and your preparation notes. These notes do not create evidence.": "الوقائع وملاحظات استعدادك. كتابة الملاحظة لا تجعلها دليلاً.",
  "Filed cases": "القضايا المؤرشفة",
  "Files unavailable": "الملفات غير متاحة",
  "No matching files": "لا توجد ملفات مطابقة",
  "Your next case awaits": "قضيتك التالية بانتظارك",
  "Hide from Terminal": "إخفاء من العرض النشط",
  "Hide key": "إخفاء المفتاح",
  "Investigation reports": "تقارير التحقيق",
  "Manage exhibit": "إدارة المعروض",
  "Prepare presentation": "تجهيز عرض الدليل",
  "Present evidence": "تقديم دليل",
  "Move to Archive": "نقل للأرشيف",
  "Archive Fact": "أرشفة الواقعة",
  "Restore to active record": "إعادة للسجل النشط",
  "Manually override to Admitted": "تعديل يدوي إلى مقبول",
  "Manually override to Marked": "تعديل يدوي إلى مرقّم",
  "Manually override to Suppress": "تعديل يدوي إلى مستبعد",
  "New conversation updates available": "توجد تحديثات جديدة للمحادثة",
  "No active case.": "لا توجد قضية نشطة.",
  "No additional description is available.": "لا يوجد وصف إضافي.",
  "No advice recorded yet.": "لم تُسجل استشارة بعد.",
  "No allegation summary has been saved for this file.": "لا يوجد ملخص اتهام محفوظ لهذا الملف.",
  "No case conversation recorded yet.": "لم تُسجل محادثة للقضية بعد.",
  "No exhibits marked yet.": "لا توجد معروضات مرقمة بعد.",
  "No facts entered yet.": "لم تُسجل وقائع بعد.",
  "No forensic notes.": "لا توجد ملاحظات فحص.",
  "No initial exhibits are listed in this file.": "لا توجد معروضات أولية في هذا الملف.",
  "No investigation reports received yet.": "لم تصل تقارير تحقيق بعد.",
  "No original sealed record is available in this legacy save.": "لا يوجد سجل حقيقة أصلي في هذا الحفظ القديم.",
  "Not provided": "غير متوفر",
  "Not yet assigned": "لم يُحدد بعد",
  "Date unavailable": "التاريخ غير متوفر",
  "Open a case from the archive to begin.": "افتح قضية من الأرشيف للبدء.",
  "Open an active case first.": "افتح قضية نشطة أولاً.",
  "Partner reviewing": "الشريك يراجع",
  "Partner’s advice notes": "ملاحظات الشريك",
  "Preparation guidance": "إرشادات التحضير",
  "Private investigation channel. The existing engine controls investigation costs.": "قناة تحقيق خاصة. تُحتسب الكلفة وفق نظام نقاط الإجراءات.",
  "Private legal strategy channel. Consultations cost 0 AP.": "قناة استشارة خاصة. الاستشارات مجانية.",
  "Private investigation channel. Actions strictly capped at 2 AP.": "قناة تحقيق خاصة. الحد الأعلى للإجراء نقطتان.",
  "Prosecution tactics": "أساليب الادعاء",
  "Random Case File": "قضية عشوائية",
  "Reading exhibits": "قراءة المعروضات",
  "Resources": "الموارد",
  "Style": "الأسلوب",
  "Temperament": "الطباع",
  "Typical tactics": "الأساليب المعتادة",
  "Your exhibit notes": "ملاحظاتك على المعروض",
  "Resolve the archive notice before accepting a case.": "عالج تنبيه الأرشيف قبل قبول قضية.",
  "Resume Active Trial": "استئناف المحاكمة الحالية",
  "Retry case setup": "إعادة إعداد القضية",
  "Review the recorded conversation for your client’s statements. This view does not introduce new testimony.": "راجع المحادثة المحفوظة لأقوال موكلك. هذا العرض لا يضيف شهادة جديدة.",
  "Review your case and prepare your next move. Writing notes does not send a message.": "راجع قضيتك وجهّز الخطوة التالية. كتابة الملاحظات لا ترسل رسالة.",
  "The recorded case conversation appears below. Only terms explicitly offered by the prosecutor are an offer; this view creates no new agreement.": "المحادثة المحفوظة أدناه. العرض هو ما اقترحه الادعاء صراحة؛ هذه الصفحة لا تنشئ اتفاقاً جديداً.",
  "Speak to DA": "تحدث إلى المدعي",
  "Speak to client": "تحدث إلى الموكل",
  "Speak to judge": "تحدث إلى القاضي",
  "Speak to partner": "تحدث إلى الشريك",
  "Speak to your client and review their statement.": "تحدث إلى موكلك وراجع إفادته.",
  "Show error": "عرض تفاصيل الخطأ",
  "Formatting error": "خطأ في تنسيق الرد",
  "Some saved information could not be opened": "تعذر فتح بعض المعلومات المحفوظة",
  "Some saved fields need recovery. Valid case data has been retained.": "بعض حقول الحفظ تحتاج استرداداً. احتُفظ ببيانات القضية السليمة.",
  "The action was saved, but the display could not refresh. Reload to continue.": "حُفظ الإجراء لكن تعذر تحديث العرض. أعد تحميل الصفحة للمتابعة.",
  "The consultation was saved, but the display could not refresh. Reload to continue.": "حُفظت الاستشارة لكن تعذر تحديث العرض. أعد تحميل الصفحة.",
  "The archive could not be read. Your active case is still available.": "تعذرت قراءة الأرشيف. ما زالت قضيتك النشطة متاحة.",
  "The archive could not read your saved collection. See the notice above.": "تعذرت قراءة المجموعة المحفوظة. راجع التنبيه أعلاه.",
  "The current trial could not be read.": "تعذرت قراءة المحاكمة الحالية.",
  "The current trial could not be read. Reload the archive before accepting a case.": "تعذرت قراءة المحاكمة الحالية. أعد تحميل الأرشيف قبل قبول قضية.",
  "The current trial has an unexpected format.": "تنسيق المحاكمة الحالية غير متوقع.",
  "The current trial cannot be read. Recover or purge it before starting another case.": "تعذرت قراءة المحاكمة الحالية. استردها أو احذفها قبل بدء أخرى.",
  "The saved case could not be read. A backup will be kept before saving.": "تعذرت قراءة الحفظ. ستُحتفظ بنسخة احتياطية قبل الحفظ.",
  "The saved collection has an unexpected format.": "تنسيق المجموعة المحفوظة غير متوقع.",
  "The saved intake is incomplete. Setup will use the valid roster, evidence and facts already in your case.": "الاستقبال المحفوظ غير مكتمل. سيستخدم الإعداد الشخصيات والأدلة والوقائع السليمة الحالية.",
  "The sealed record is available after the trial ends.": "تُكشف الحقيقة المحفوظة بعد نهاية المحاكمة.",
  "The trial controls are unavailable. Reload the page and try again.": "أدوات المحاكمة غير متاحة. أعد تحميل الصفحة وحاول مجدداً.",
  "The trial could not be started.": "تعذر بدء المحاكمة.",
  "This action was interrupted. Retry when ready.": "انقطع الإجراء. أعد المحاولة عندما تكون مستعداً.",
  "This case does not contain all information needed to begin a trial.": "تنقص هذه القضية معلومات لازمة لبدء المحاكمة.",
  "This case is no longer in the archive. Close the file and refresh the collection.": "لم تعد القضية في الأرشيف. أغلق الملف وحدّث المجموعة.",
  "This file is missing information needed to begin a trial. You can still review what is available.": "تنقص الملف معلومات لبدء المحاكمة، ويمكنك مراجعة الموجود.",
  "This saved reply could not be read as dialogue.": "تعذرت قراءة الرد المحفوظ كمحادثة.",
  "This trial changed in another tab. Reload to use the latest saved case.": "تغيرت المحاكمة في تبويب آخر. أعد التحميل لاستخدام أحدث حفظ.",
  "This trial changed in another tab. Reload to use the latest saved case. Keep a copy of any unsent text before reloading.": "تغيرت المحاكمة في تبويب آخر. احتفظ بنسخة من النص غير المرسل ثم أعد التحميل.",
  "Traits are unavailable for this prosecutor.": "صفات هذا المدعي غير متاحة.",
  "Try another search or clear the filters to browse the whole collection.": "جرّب بحثاً آخر أو امسح عوامل التصفية لعرض المجموعة.",
  "Type CONFIRM to continue.": "اكتب CONFIRM للمتابعة.",
  "Type exactly 'CONFIRM'": "اكتب CONFIRM تماماً",
  "Unnamed exhibit": "معروض دون اسم",
  "Untitled case": "قضية دون عنوان",
  "Wait for the current action to finish before purging the case.": "انتظر انتهاء الإجراء الحالي قبل حذف القضية.",
  "Wait for the current action to finish before changing language.": "انتظر انتهاء الإجراء الحالي قبل تغيير اللغة.",
  "Could not save language preference. Your current page remains open.": "تعذر حفظ اللغة. ستبقى الصفحة الحالية مفتوحة.",
  "Waiting for a reply…": "انتظار الرد…",
  "Taking longer than usual…": "استغرق الرد وقتاً أطول…",
  "You currently have an active trial. Accepting this case will permanently discard your active progress. Proceed?": "لديك محاكمة نشطة. قبول هذه القضية سيحذف تقدم المحاكمة الحالية نهائياً. هل تريد المتابعة؟",
  "Your case is ready. Begin with your client or review the file.": "قضيتك جاهزة. ابدأ مع موكلك أو راجع الملف.",
  "Your draft could not be saved. Keep this page open.": "تعذر حفظ المسودة. أبقِ الصفحة مفتوحة.",
  "Your senior partner is available for a private consultation.": "الشريك الأقدم متاح لاستشارة خاصة.",
  "Browser storage is unavailable. Saving may fail.": "تخزين المتصفح غير متاح، وقد لا ينجح الحفظ.",
  "Could not read the latest case. Reload before continuing.": "تعذرت قراءة آخر حفظ. أعد تحميل الصفحة قبل المتابعة.",
  "Could not save pending cases. Check browser storage.": "تعذر حفظ القضايا الجديدة. تحقق من تخزين المتصفح.",
  "Could not save the archive. Check browser storage.": "تعذر حفظ الأرشيف. تحقق من تخزين المتصفح.",
  "Could not save this case. Your browser storage may be full or unavailable. Keep this page open to retain unsaved text.": "تعذر حفظ القضية. قد يكون التخزين ممتلئاً أو غير متاح. أبقِ الصفحة مفتوحة للاحتفاظ بالنص غير المحفوظ.",
  "Saved case collection is damaged.": "مجموعة القضايا المحفوظة تالفة.",
  "Search cancelled.": "أُلغي البحث.",
  "Request already ended.": "انتهى الطلب بالفعل.",
  "A saved case entry is not readable.": "تعذرت قراءة أحد ملفات القضايا.",
  "A saved reply has an unreadable dialogue format.": "تنسيق محادثة أحد الردود المحفوظة غير قابل للقراءة.",
  "An exhibit with this identifier already exists. Choose a different identifier.": "يوجد معروض بهذا الرقم. اختر رقماً مختلفاً.",
  "Finish case setup before requesting a consultation.": "أكمل إعداد القضية قبل طلب استشارة.",
  "Finish case setup before sending a trial action.": "أكمل إعداد القضية قبل إرسال إجراء للمحكمة.",
  "The server returned an empty or invalid reply.": "أعاد الخادم رداً فارغاً أو غير صالح.",
  "The server returned an empty or invalid reply. No case update was applied.": "أعاد الخادم رداً فارغاً أو غير صالح. لم تتغير القضية.",
  "The server returned invalid JSON.": "أعاد الخادم بيانات JSON غير صالحة.",
  "Invalid model metadata. No case update was applied.": "بيانات المحرك غير صالحة. لم تتغير القضية.",
  "The reply contains multiple state checkpoints.": "يحتوي الرد أكثر من سجل تحديث للحالة.",
  "The state checkpoint is incomplete.": "سجل تحديث الحالة غير مكتمل.",
  "The state checkpoint is not valid JSON.": "سجل الحالة ليس JSON صالحاً.",
  "The state checkpoint must be an object.": "سجل الحالة يجب أن يكون كائن بيانات.",
  "Checkpoint cannot change the client occupation.": "لا يجوز للتحديث تغيير مهنة الموكل المثبتة.",
  "Checkpoint has conflicting client occupations.": "التحديث يحتوي مهناً متعارضة للموكل.",
  "Checkpoint docket must be a list.": "سجل المعروضات في التحديث يجب أن يكون قائمة.",
  "Checkpoint facts must be a list of text.": "الوقائع في التحديث يجب أن تكون قائمة نصوص.",
  "Invalid checkpoint case.": "معلومات القضية في التحديث غير صالحة.",
  "Invalid checkpoint trialEnded.": "علامة نهاية المحاكمة في التحديث غير صالحة.",
  "Duplicate exhibit identifiers.": "أرقام معروضات مكررة.",
  "Starter exhibit identifiers must be unique.": "يجب ألا تتكرر أرقام المعروضات الأولية.",
  "Setup response did not initialize the roster and two starter exhibits. Retry setup.": "لم يُكمل الرد الشخصيات والمعروضين الأوليين. أعد محاولة الإعداد.",
  "Setup response is missing its state checkpoint. Retry setup.": "رد الإعداد ينقصه سجل تحديث الحالة. أعد المحاولة.",
  "The saved intake has an invalid client occupation.": "مهنة الموكل في الاستقبال المحفوظ غير صالحة.",
  "The saved intake has an invalid complexity.": "مستوى التعقيد المحفوظ غير صالح.",
  "The saved intake has conflicting client occupations.": "مهن الموكل المحفوظة متعارضة.",
  "The saved intake is missing its case seed or scout record.": "تنقص الاستقبال المحفوظ بيانات إنشاء القضية أو ملخصها.",
  "The saved intake needs two starter exhibits.": "يحتاج الاستقبال المحفوظ معروضين أوليين.",
  "An exhibit must be an object.": "المعروض يجب أن يكون كائن بيانات.",
  "An exhibit has an invalid identifier.": "رقم المعروض غير صالح.",
  "AP cannot increase without an eligible trial development.": "لا تزيد النقاط دون تطور مؤهل في المحاكمة.",
  "AP grants require a new court development during trial.": "منح النقاط يحتاج تطوراً جديداً في المحاكمة.",
  "AP grants must reference newly disclosed evidence or a fact.": "يجب ربط النقاط بدليل أو واقعة جديدة كُشف عنها.",
  "A reply cannot spend more than 2 AP.": "لا يجوز لرد واحد إنفاق أكثر من نقطتين.",
  "An investigation cannot increase AP or spend more than 2 AP.": "لا يزيد التحقيق النقاط ولا ينفق أكثر من نقطتين.",
  "An AP development must reference one new fact or exhibit.": "يجب ربط التطور بواقعة أو معروض جديد واحد.",
  "Invalid AP development identifier or reason.": "رقم تطور النقاط أو سببه غير صالح.",
  "Incorrect AP total for the trial development.": "رصيد النقاط لا يطابق التطور.",
  "The case has reached its trial development AP allowance.": "بلغت القضية حد النقاط الإضافية للتطورات.",
  "Consultations cannot update case resources.": "الاستشارات لا تغير موارد القضية.",
  "Cell Tower Telemetry & Pings": "بيانات أبراج الهاتف واتصالاته",
  "911 Dispatch & CAD Run Logs": "صوت الطوارئ وسجلات البلاغات [CAD]",
  "Transit Turnstile & Badge Logs": "سجلات المواصلات وبطاقات الدخول",
  "Bank & Transaction Records": "سجلات البنوك والتحويلات",
  "Optical Sensors / CCTV Sweep": "البحث في كاميرات المراقبة [CCTV]",
  "Forensic Biological / Ballistics Audit": "مراجعة الحمض النووي والمقذوفات",
  "Carrier timing offsets": "فروق ساعات شركة الاتصالات",
  "Audio buffer": "التسجيل الصوتي",
  "Access telemetry": "بيانات الدخول",
  "Financial timeline": "التسلسل المالي",
  "Field video canvass": "بحث ميداني عن فيديو",
  "Independent re-test": "إعادة فحص مستقل",
  "2 Initial Exhibits Marked": "رُقّم معروضان أوليان",
  "TIP: A hostile witness cannot be lead on cross-examination... wait, yes they can.": "تلميح: يجوز عادة استخدام الأسئلة الموحية في الاستجواب المضاد.",
  "TIP: Consult your Senior Partner (/consult) without spending any AP.": "تلميح: استشارة الشريك عبر /consult مجانية.",
  "TIP: Object with FRE 404(b) whenever the DA brings up uncharged bad acts.": "تلميح: اختبر الغرض من ذكر أفعال سابقة وفق FRE 404(b)؛ ليس كل ذكر لها ممنوعاً.",
  "TIP: Premeditation turns 2nd Degree Murder into 1st Degree.": "تلميح: افحص دليل التخطيط عند مناقشة القتل من الدرجة الأولى.",
  "TIP: Subpoenas cost 1 AP. All investigative actions are capped at 2 AP maximum.": "تلميح: طلب السجلات يكلف نقطة؛ الحد الأعلى للتحقيق في الرد نقطتان.",
  "TIP: Suppressing tainted evidence removes all derivative fruits under the 4th Amendment.": "تلميح: قد يؤثر استبعاد الدليل على أدلة مشتقة منه، مع وجود استثناءات.",
  "Your saved data has not been changed. Case acceptance is unavailable until the files can be read.": "لم تتغير بياناتك المحفوظة. يتوقف قبول القضايا حتى يمكن قراءة الملفات.",
  "Shelf": "الرف",
  "State v. Doe": "الولاية ضد دو",
  "State v. Null": "الولاية ضد —",
  "Untitled": "دون عنوان",
  "Case": "القضية",
  "Created": "تاريخ الإنشاء",
  "Chapter": "القسم",
  "Investigation": "التحقيق",
  "Trial": "المحاكمة",
  "Closing": "المرافعة الختامية",
  "Verdict": "النتيجة",
  "Charges & proof": "التهم وما يجب إثباته",
  "Plain-English guides": "شروح مبسطة",
  "How to use it": "كيف تستخدمه؟",
  "Example in practice": "مثال عملي",
  "Burden of proof & reasonable doubt": "عبء الإثبات والشك المعقول [Burden of proof & reasonable doubt]",
  "Elements & mental state (mens rea)": "عناصر الجريمة والقصد الجنائي [Elements & mental state (mens rea)]",
  "Self-defense & who attacked first": "الدفاع عن النفس ومن بدأ الاعتداء [Self-defense & who attacked first]",
  "Excluding illegally obtained evidence": "استبعاد الأدلة التي جُمعت بصورة غير قانونية [Excluding illegally obtained evidence]",
  "Discovery, Brady & Giglio disclosure": "الكشف عن معلومات القضية وأدلة برادي وغيغليو [Discovery, Brady & Giglio disclosure]",
  "Foundation, authentication & admission": "تأسيس الدليل والتحقق من أصالته وقبوله [Foundation, authentication & admission]",
  "Impeachment: testing credibility": "اختبار مصداقية الشاهد [Impeachment: testing credibility]",
  "Objections, motions & rulings": "الاعتراضات والطلبات وقرارات القاضي [Objections, motions & rulings]",
  "Hearsay": "الشهادة السماعية [Hearsay]",
  "Common hearsay exceptions & opposing-party statements": "استثناءات الشهادة السماعية وأقوال الخصم [Common hearsay exceptions & opposing-party statements]",
  "Leading questions on direct examination": "الأسئلة الموحية أثناء الاستجواب المباشر [Leading questions on direct examination]",
  "Personal knowledge & speculation": "المعرفة الشخصية والتخمين [Personal knowledge & speculation]",
  "Prior bad acts & improper character evidence": "الأفعال السابقة وأدلة الشخصية غير المسموح بها [Prior bad acts & improper character evidence]",
  "Unfair prejudice": "التأثير غير العادل على القرار [Unfair prejudice]",
  "Assumes facts not in evidence": "افتراض وقائع لم تُثبت [Assumes facts not in evidence]",
  "Compound questions": "الأسئلة المركبة [Compound questions]",
  "Argumentative or repetitive questioning": "الأسئلة الجدلية أو المتكررة [Argumentative or repetitive questioning]",
  "Ordinary witnesses giving expert conclusions": "استنتاجات الخبراء على لسان شاهد عادي [Ordinary witnesses giving expert conclusions]",
  "Expert reliability & a Daubert challenge": "موثوقية الخبير واختبار دوبرت [Expert reliability & a Daubert challenge]",
  "Confronting an absent accuser": "حق مواجهة صاحب الاتهام [Confronting an absent accuser]",
  "Relevance": "صلة الدليل بالقضية [Relevance]",
  "First-Degree Murder": "القتل من الدرجة الأولى [First-Degree Murder]",
  "Second-Degree Murder": "القتل من الدرجة الثانية [Second-Degree Murder]",
  "Aggravated Assault with a Deadly Weapon": "الاعتداء المشدد بسلاح خطير [Aggravated Assault with a Deadly Weapon]",
  "Armed Robbery": "السطو المسلح [Armed Robbery]",
  "Kidnapping / False Imprisonment": "الاختطاف أو الاحتجاز غير المشروع [Kidnapping / False Imprisonment]",
  "Aggravated Battery Causing Great Bodily Harm": "الإيذاء المشدد المسبب لإصابة جسيمة [Aggravated Battery Causing Great Bodily Harm]",
  "Attempted Murder": "الشروع في القتل [Attempted Murder]",
  "Wire Fraud (18 U.S.C. § 1343)": "الاحتيال عبر الاتصالات الإلكترونية [Wire Fraud (18 U.S.C. § 1343)]",
  "Securities Fraud / Insider Trading": "الاحتيال في الأوراق المالية والتداول بمعلومات داخلية [Securities Fraud / Insider Trading]",
  "Embezzlement & Corporate Misappropriation": "الاختلاس وإساءة استخدام ممتلكات الشركة [Embezzlement & Corporate Misappropriation]",
  "Unauthorized Computer Access (CFAA - 18 U.S.C. § 1030)": "الدخول غير المصرح به إلى الحاسوب [Unauthorized Computer Access (CFAA - 18 U.S.C. § 1030)]",
  "Digital Extortion & Ransomware Deployment": "الابتزاز الرقمي وبرامج الفدية [Digital Extortion & Ransomware Deployment]",
  "Aggravated Identity Theft (18 U.S.C. § 1028A)": "سرقة الهوية المشددة [Aggravated Identity Theft (18 U.S.C. § 1028A)]",
  "Trade Secret Theft & Corporate Espionage": "سرقة الأسرار التجارية والتجسس على الشركات [Trade Secret Theft & Corporate Espionage]",
  "Possession with Intent to Distribute (PWID)": "حيازة بقصد التوزيع [Possession with Intent to Distribute (PWID)]",
  "Conspiracy to Traffic Narcotics (21 U.S.C. § 846)": "التآمر على الاتجار بالمخدرات [Conspiracy to Traffic Narcotics (21 U.S.C. § 846)]",
  "Operating a Drug-Involved Premises": "إدارة مكان لنشاط مخدرات [Operating a Drug-Involved Premises]",
  "Illicit Pharmaceutical & Precursor Diversion": "تحويل الأدوية والمواد الأولية إلى استخدام غير مشروع [Illicit Pharmaceutical & Precursor Diversion]",
  "Simple Felony Possession": "الحيازة البسيطة المصنفة جناية [Simple Felony Possession]",
  "Voluntary Manslaughter (Heat of Passion / Imperfect Self-Defense)": "القتل العمد مع ظروف مخففة [Voluntary Manslaughter (Heat of Passion / Imperfect Self-Defense)]",
  "Involuntary Manslaughter / Gross Criminal Negligence": "القتل غير العمد أو الإهمال الجنائي الجسيم [Involuntary Manslaughter / Gross Criminal Negligence]",
  "Vehicular Manslaughter with Gross Negligence": "القتل بالمركبة مع إهمال جسيم [Vehicular Manslaughter with Gross Negligence]",
  "Prosecutorial Overcharge: Felony Murder Elevation": "المبالغة في التهمة والقتل المرتبط بجناية [Prosecutorial Overcharge: Felony Murder Elevation]",
  "Reckless Endangerment Resulting in Death": "تعريض الحياة للخطر بتهور أدى إلى وفاة [Reckless Endangerment Resulting in Death]",
  "Anonymous tips & the basis for a stop": "البلاغات المجهولة وأساس استيقاف الشخص [Anonymous tips & the basis for a stop]",
  "Suggestive identification": "التعرّف على المشتبه به بتأثير موحٍ [Suggestive identification]",
  "Disputed consent to search": "الموافقة المتنازع عليها على التفتيش [Disputed consent to search]",
  "Search beyond a warrant": "تجاوز حدود أمر التفتيش [Search beyond a warrant]",
  "Chain of custody & authenticity": "سلسلة حيازة الدليل وأصالته [Chain of custody & authenticity]",
  "Questioning after rights are invoked": "الاستجواب بعد التمسك بالحقوق [Questioning after rights are invoked]",
  "Hidden witness agreements": "الاتفاقات المخفية مع الشهود [Hidden witness agreements]",
  "Unreliable scientific methods": "الأساليب العلمية غير الموثوقة [Unreliable scientific methods]",
  "Poor observation conditions": "ظروف مشاهدة ضعيفة [Poor observation conditions]",
  "Grudges & prior disputes": "الضغائن والخلافات السابقة [Grudges & prior disputes]",
  "Financial self-interest": "المصلحة المالية [Financial self-interest]",
  "Changed stories": "تغيّر الروايات [Changed stories]",
  "Cooperating co-defendants & plea deals": "شركاء متهمون متعاونون واتفاقات الإقرار [Cooperating co-defendants & plea deals]",
  "Career or professional pressure": "ضغوط الوظيفة أو المهنة [Career or professional pressure]",
  "Flight for an unrelated warrant": "الهروب بسبب أمر توقيف آخر [Flight for an unrelated warrant]",
  "Protecting another person": "حماية شخص آخر [Protecting another person]",
  "A different uncharged act": "فعل مختلف لم تُوجّه به التهمة [A different uncharged act]",
  "Evidence destroyed for another reason": "إتلاف دليل لسبب آخر [Evidence destroyed for another reason]",
  "Prior felony history & fear of authorities": "سوابق الجنايات والخوف من السلطات [Prior felony history & fear of authorities]",
  "Past-bad-act ambush": "مباغتة الدفاع بأفعال سابقة [Past-bad-act ambush]",
  "Loaded, compound questions": "أسئلة مشحونة ومركبة [Loaded, compound questions]",
  "Ordinary witness giving technical conclusions": "استنتاجات تقنية من شاهد غير خبير [Ordinary witness giving technical conclusions]",
  "Concealed benefits for a witness": "إخفاء المنافع الموعودة للشاهد [Concealed benefits for a witness]",
  "Hearsay disguised as investigation background": "إخفاء القول السماعي تحت عنوان خلفية التحقيق [Hearsay disguised as investigation background]",
  "Phone location & timing records": "سجلات موقع الهاتف وتوقيته [Phone location & timing records]",
  "Dispatch logs & emergency audio": "سجلات البلاغات وصوت مكالمات الطوارئ [Dispatch logs & emergency audio]",
  "Travel & access records": "سجلات السفر والدخول [Travel & access records]",
  "Medical, intake & shift records": "السجلات الطبية وسجلات الوصول والعمل [Medical, intake & shift records]",
  "Find route & shift witnesses": "البحث عن شهود الطريق والوردية [Find route & shift witnesses]",
  "Locate independent video": "العثور على فيديو مستقل [Locate independent video]",
  "Biological & ballistics review": "مراجعة الحمض النووي والمقذوفات [Biological & ballistics review]",
  "Digital & instrument review": "مراجعة البيانات الرقمية والأجهزة [Digital & instrument review]",
  "Discarded Heavy Work Glove": "قفاز عمل سميك متروك [Discarded Heavy Work Glove]",
  "Point-of-Sale Register Receipt": "إيصال صندوق البيع [Point-of-Sale Register Receipt]",
  "Low-Resolution Forecourt CCTV Snippet": "مقطع كاميرا منخفض الدقة [Low-Resolution Forecourt CCTV Snippet]",
  "Serrated Utility Box Cutter": "قاطع صناديق مسنن [Serrated Utility Box Cutter]",
  "Handwritten Shift Manifest & Notes": "سجل وردية وملاحظات بخط اليد [Handwritten Shift Manifest & Notes]",
  "Equipment Maintenance Sign-Off Card": "بطاقة اعتماد صيانة المعدات [Equipment Maintenance Sign-Off Card]",
  "Transit Badge Keycard Scan Log": "سجل مسح بطاقة دخول [Transit Badge Keycard Scan Log]",
  "Patrol Dashcam Pre-Event Buffer Clip": "مقطع كاميرا الدورية قبل بدء التسجيل [Patrol Dashcam Pre-Event Buffer Clip]",
  "Field Presumptive Chemical Test Vial": "عينة اختبار كيميائي ميداني أولي [Field Presumptive Chemical Test Vial]",
  "Intermodal Bolt Seal Manifest": "سجل أختام حاوية الشحن [Intermodal Bolt Seal Manifest]",
  "Hospital Emergency Toxicology Panel": "فحص السموم في قسم الطوارئ [Hospital Emergency Toxicology Panel]",
  "Autopsy Anatomical Wound Schematic": "مخطط مواضع الجروح في التشريح [Autopsy Anatomical Wound Schematic]",
  "Extracted Encrypted Messaging Log": "سجل رسائل مشفرة مستخرج [Extracted Encrypted Messaging Log]",
  "Remote Server Bastion Auth Log": "سجل الدخول عبر خادم وسيط [Remote Server Bastion Auth Log]",
  "Laboratory Gas Chromatograph Calibration Readout": "سجل معايرة جهاز الفصل الغازي [Laboratory Gas Chromatograph Calibration Readout]",
  "Automated Clearinghouse Wire Trace": "مسار تحويل مالي إلكتروني [Automated Clearinghouse Wire Trace]",
  "Violent crimes: identity & the first aggressor": "ختام قضايا العنف: الهوية ومن بدأ الاعتداء [Violent crimes: identity & the first aggressor]",
  "Financial cases: dishonest intent": "ختام القضايا المالية: القصد غير الأمين [Financial cases: dishonest intent]",
  "Cyber cases: attribution & data integrity": "ختام القضايا الرقمية: نسبة الفعل وسلامة البيانات [Cyber cases: attribution & data integrity]",
  "Drug cases: knowledge, control & distribution purpose": "ختام قضايا المخدرات: العلم والسيطرة وغرض التوزيع [Drug cases: knowledge, control & distribution purpose]",
  "Overcharging & manslaughter: the proper mental state": "ختام المبالغة في التهمة: الحالة الذهنية الصحيحة [Overcharging & manslaughter: the proper mental state]",
  "Judge Arthur Pendelton": "القاضي آرثر بندلتون [Judge Arthur Pendelton]",
  "Judge Evelyn Ramos": "القاضية إيفلين راموس [Judge Evelyn Ramos]",
  "Judge Kenneth Choi": "القاضي كينيث تشوي [Judge Kenneth Choi]",
  "Judge Mirah Al-Hassan": "القاضية ميرا الحسن [Judge Mirah Al-Hassan]",
  "Judge Raymond Callahan": "القاضي ريموند كالاهان [Judge Raymond Callahan]",
  "Judge Patricia De La Torre": "القاضية باتريشيا دي لا توري [Judge Patricia De La Torre]",
  "ADA Gregory Thorne": "مساعد المدعي العام غريغوري ثورن [ADA Gregory Thorne]",
  "ADA Samantha Ward": "مساعدة المدعي العام سامانثا وارد [ADA Samantha Ward]",
  "ADA Tariq Mansour": "مساعد المدعي العام طارق منصور [ADA Tariq Mansour]",
  "ADA Elena Rostova": "مساعدة المدعي العام إيلينا روستوفا [ADA Elena Rostova]",
  "ADA Marcus Delaney": "مساعد المدعي العام ماركوس ديلاني [ADA Marcus Delaney]",
  "ADA Chloe Zhang": "مساعدة المدعي العام كلوي تشانغ [ADA Chloe Zhang]",
  "A rigid traditionalist who views the courtroom as an arena of strict procedural discipline. Pendelton has zero patience for theatrical speeches, speaking objections, or vague arguments.": "قاضٍ صارم في الإجراءات يطلب أسباباً دقيقة ولا يحب التخمين. اعترض بإيجاز مع تحديد القاعدة والدليل، وتجنب الخطب والنظريات بلا أساس.",
  "Pedantic, easily irritated by improper FRE phrasing, impatient with speaking objections.": "قاضٍ صارم في الإجراءات يطلب أسباباً دقيقة ولا يحب التخمين. اعترض بإيجاز مع تحديد القاعدة والدليل، وتجنب الخطب والنظريات بلا أساس.",
  "Sustains strict technical objections; penalizes speculative defense lines quickly.": "قاضٍ صارم في الإجراءات يطلب أسباباً دقيقة ولا يحب التخمين. اعترض بإيجاز مع تحديد القاعدة والدليل، وتجنب الخطب والنظريات بلا أساس.",
  "He expects attorneys to cite specific Federal Rules of Evidence numbers without hesitation. If counsel begins giving long-winded commentary before the jury instead of stating the black-letter rule, he will cut them off immediately. He sustains narrow, technical objections and quickly penalizes any defense cross-examination that drifts into speculation.": "قاضٍ صارم في الإجراءات يطلب أسباباً دقيقة ولا يحب التخمين. اعترض بإيجاز مع تحديد القاعدة والدليل، وتجنب الخطب والنظريات بلا أساس.",
  "Keep every objection sharp, formal, and strictly tied to the exact rule number. Never argue with him after a ruling, and avoid speculative theories unless you have physical exhibits already marked to support them.": "اعترض بإيجاز مع تحديد القاعدة والدليل، وتجنب الخطب والنظريات بلا أساس.",
  "Textualist / Procedure-Strict": "قاضٍ صارم في الإجراءات يطلب أسباباً دقيقة ولا يحب التخمين.",
  "A pragmatic docket commander focused entirely on efficiency, clarity, and pacing. Ramos manages one of the busiest dockets in the district and despises wasted trial time.": "قاضية سريعة الإيقاع تفضل أسئلة عملية ومركزة. تحرك نحو تناقض مفيد دون تكرار غير لازم.",
  "Fast-paced, values courtroom efficiency, hates redundant questioning or theatrical pauses.": "قاضية سريعة الإيقاع تفضل أسئلة عملية ومركزة. تحرك نحو تناقض مفيد دون تكرار غير لازم.",
  "Gives latitude to cross-examination as long as it moves rapidly toward a concrete point.": "قاضية سريعة الإيقاع تفضل أسئلة عملية ومركزة. تحرك نحو تناقض مفيد دون تكرار غير لازم.",
  "She becomes visibly annoyed by slow foundational setups, repetitive witness questioning, and dramatic pauses meant for the jury. However, she gives defense counsel wide latitude on cross-examination as long as counsel moves rapidly and attacks direct contradictions without stalling.": "قاضية سريعة الإيقاع تفضل أسئلة عملية ومركزة. تحرك نحو تناقض مفيد دون تكرار غير لازم.",
  "Get straight to the contradiction. Skip lengthy build-ups and confront state witnesses directly. If she senses you are fishing or stalling for time, she will sustain prosecution relevance objections without hesitation.": "تحرك نحو تناقض مفيد دون تكرار غير لازم.",
  "Pragmatic / Docket-Pacing": "قاضية سريعة الإيقاع تفضل أسئلة عملية ومركزة.",
  "A detail-obsessed jurist with a deep appreciation for forensic science, data hygiene, and technical documentation. Emotional appeals and courtroom rhetoric completely bounce off him.": "يهتم بالتفاصيل العلمية والسجلات وتداول الأدلة. اربط الدفع بالحيازة والموثوقية والساعات والخلل المحدد.",
  "Analytical, listens intensely to foundation and chain of custody, ignores emotional appeals.": "يهتم بالتفاصيل العلمية والسجلات وتداول الأدلة. اربط الدفع بالحيازة والموثوقية والساعات والخلل المحدد.",
  "Highly receptive to suppression motions when technical custody records are flawed.": "يهتم بالتفاصيل العلمية والسجلات وتداول الأدلة. اربط الدفع بالحيازة والموثوقية والساعات والخلل المحدد.",
  "Choi listens intently to evidence foundation, calibration logs, and transit custody sheets. Unlike many judges, he will not give the state the benefit of the doubt on sloppy police paperwork. If an officer cannot verify exact timestamps or custody transfers, Choi will entertain technical defense suppression motions.": "يهتم بالتفاصيل العلمية والسجلات وتداول الأدلة. اربط الدفع بالحيازة والموثوقية والساعات والخلل المحدد.",
  "Audit laboratory logs, timestamps, and transit custody forms. Suppression motions carry significant weight with him. Never attempt to sway him with emotional appeals or moral outrage—stick strictly to technical errors.": "اربط الدفع بالحيازة والموثوقية والساعات والخلل المحدد.",
  "Forensic / Detail-Obsessed": "يهتم بالتفاصيل العلمية والسجلات وتداول الأدلة.",
  "A deliberate, constitutionalist jurist who treats Fourth and Fifth Amendment protections as sacred guardrails. She holds prosecutors to the highest constitutional standards.": "تفحص الحقوق الدستورية وواجبات الكشف عن الأدلة بعناية. راجع صلاحية التفتيش والاستجواب أثناء الاحتجاز ومنافع الشهود المخفية.",
  "Calm, deliberate, fiercely protective of Brady obligations and 4th/5th Amendment boundaries.": "تفحص الحقوق الدستورية وواجبات الكشف عن الأدلة بعناية. راجع صلاحية التفتيش والاستجواب أثناء الاحتجاز ومنافع الشهود المخفية.",
  "Holds prosecutors to strict standards on warrantless actions; tolerates aggressive defense inquiry.": "تفحص الحقوق الدستورية وواجبات الكشف عن الأدلة بعناية. راجع صلاحية التفتيش والاستجواب أثناء الاحتجاز ومنافع الشهود المخفية.",
  "She is deeply skeptical of warrantless searches, broad protective sweeps, and secretive cooperation deals between the state and jailhouse witnesses. She protects defense cross-examination when challenging police overreach and will readily order the state to turn over concealed discovery.": "تفحص الحقوق الدستورية وواجبات الكشف عن الأدلة بعناية. راجع صلاحية التفتيش والاستجواب أثناء الاحتجاز ومنافع الشهود المخفية.",
  "Scrutinize every search warrant, vehicle stop, and witness concession. If police stepped outside their legal authority, file suppression motions immediately. Al-Hassan will not let prosecutors gloss over civil liberties violations.": "راجع صلاحية التفتيش والاستجواب أثناء الاحتجاز ومنافع الشهود المخفية.",
  "Constitutionalist / Defense-Fair": "تفحص الحقوق الدستورية وواجبات الكشف عن الأدلة بعناية.",
  "A gruff, veteran jurist with deep ties to the law enforcement community. Callahan has little patience for novel legal theories or what he perceives as procedural defense obstruction.": "قاضٍ تقليدي يميل للثقة بشهادة الشرطة ويتشكك في البدائل غير المدعومة. استخدم نبرة هادئة وسجلات بدلاً من الاتهامات.",
  "Gruff, old-school, skeptical of technical defense motions, values police credibility.": "قاضٍ تقليدي يميل للثقة بشهادة الشرطة ويتشكك في البدائل غير المدعومة. استخدم نبرة هادئة وسجلات بدلاً من الاتهامات.",
  "Issues strikes quickly for defense badgering; skeptical of alternative suspect theories.": "قاضٍ تقليدي يميل للثقة بشهادة الشرطة ويتشكك في البدائل غير المدعومة. استخدم نبرة هادئة وسجلات بدلاً من الاتهامات.",
  "He instinctively trusts police testimony and gives state witnesses significant leeway. If defense counsel attacks an officer with an aggressive or badgering tone, Callahan will issue judicial strikes quickly. He routinely dismisses speculative alternative suspect theories.": "قاضٍ تقليدي يميل للثقة بشهادة الشرطة ويتشكك في البدائل غير المدعومة. استخدم نبرة هادئة وسجلات بدلاً من الاتهامات.",
  "Do not confront police officers with aggressive rhetoric or emotional accusations. You must impeach officers using written CAD dispatch records, antenna timing data, and hard physical logs rather than vocal tone. Let the paper expose the contradiction.": "استخدم نبرة هادئة وسجلات بدلاً من الاتهامات.",
  "Pro-Law-Enforcement / Traditionalist": "قاضٍ تقليدي يميل للثقة بشهادة الشرطة ويتشكك في البدائل غير المدعومة.",
  "A cerebral, academic jurist who decides motions based entirely on statutory text, legal precedent, and strict element-by-element statutory analysis.": "تركز على عناصر التهمة وقواعد الأدلة. قسّم التهمة إلى المطلوب إثباته واربط كل طلب بالدليل الناقص.",
  "Cerebral, demands precise citations of statutory elements, unmoved by dramatic rhetoric.": "تركز على عناصر التهمة وقواعد الأدلة. قسّم التهمة إلى المطلوب إثباته واربط كل طلب بالدليل الناقص.",
  "Rules purely on black-letter evidentiary precedent regardless of who objects.": "تركز على عناصر التهمة وقواعد الأدلة. قسّم التهمة إلى المطلوب إثباته واربط كل طلب بالدليل الناقص.",
  "De La Torre remains entirely dispassionate throughout trial. She cannot be charmed by charismatic storytelling or rattled by fiery closing arguments. When ruling on objections or dismissals, she requires attorneys to articulate exactly which statutory element or evidentiary precedent applies.": "تركز على عناصر التهمة وقواعد الأدلة. قسّم التهمة إلى المطلوب إثباته واربط كل طلب بالدليل الناقص.",
  "Frame all motions and jury arguments around statutory definitions and necessary mental states. When arguing for an acquittal or directed verdict, break the charge down element-by-element to show where the prosecution failed to meet its legal burden.": "قسّم التهمة إلى المطلوب إثباته واربط كل طلب بالدليل الناقص.",
  "Even-Handed / Academic": "تركز على عناصر التهمة وقواعد الأدلة.",
  "An aggressive, heavy-hitting prosecutor who uses relentless pressure and intimidating questioning to force defendants into traps and contradictions.": "يستخدم الضغط والتلميح إلى الأفعال السابقة. انتبه للاستعمال غير المسموح للشخصية واعترض قبل إضافة تفاصيل مؤثرة.",
  "Relentless, pushes witnesses hard, uses leading questions to trap hesitant defendants.": "يستخدم الضغط والتلميح إلى الأفعال السابقة. انتبه للاستعمال غير المسموح للشخصية واعترض قبل إضافة تفاصيل مؤثرة.",
  "Thorne leans heavily on juror prejudice. His preferred tactic is slipping in uncharged prior misconduct, past arrests, and negative character evidence under Rule 404(b) unless defense counsel cuts him off immediately. He pushes hesitant witnesses hard with leading questions.": "يستخدم الضغط والتلميح إلى الأفعال السابقة. انتبه للاستعمال غير المسموح للشخصية واعترض قبل إضافة تفاصيل مؤثرة.",
  "Keep Rule 404(b) (Prior Bad Acts / Character Propensity) ready on your tongue. The moment he hints at uncharged past history or tries to paint your client as a generally bad person, object instantly before the jury absorbs the prejudice.": "انتبه للاستعمال غير المسموح للشخصية واعترض قبل إضافة تفاصيل مؤثرة.",
  "Bulldozer / Aggressive": "يستخدم الضغط والتلميح إلى الأفعال السابقة.",
  "Attempts to introduce prejudicial character evidence under FRE 404(b) unless objected to.": "يستخدم الضغط والتلميح إلى الأفعال السابقة.",
  "A quiet, methodical prosecutor who avoids theatrics and builds circumstantial cases like an engineer assembling blueprints.": "تبني القضية منهجياً من السجلات والروابط التقنية. افحص المعايرة والتوقيت والصلاحيات وحدود كل سجل.",
  "Methodical, quiet, builds circumstantial evidence block-by-block with documents.": "تبني القضية منهجياً من السجلات والروابط التقنية. افحص المعايرة والتوقيت والصلاحيات وحدود كل سجل.",
  "Ward relies on cellular telemetry, electronic access logs, financial trails, and physical paper. She rarely makes procedural errors and maintains an airtight chain of custody. Rather than relying on emotional victim testimony, she overwhelms juries with corroborating technical data.": "تبني القضية منهجياً من السجلات والروابط التقنية. افحص المعايرة والتوقيت والصلاحيات وحدود كل سجل.",
  "Do not waste time attacking the veracity or demeanor of state witnesses. Instead, attack technical calibration dates, carrier timing offsets, and timestamp discrepancies in her logs. Look for digital margins of error rather than overt lies.": "افحص المعايرة والتوقيت والصلاحيات وحدود كل سجل.",
  "Forensic Precisionist": "تبني القضية منهجياً من السجلات والروابط التقنية.",
  "Relies heavily on digital logs and phone records; rarely loses chain of custody.": "تبني القضية منهجياً من السجلات والروابط التقنية.",
  "A charismatic courtroom orator who connects effortlessly with juries by spinning dramatic, emotionally charged narratives centered on victim sympathy.": "يستخدم روايات عاطفية وأقوالاً منقولة. اختبر السماع وميّز الدليل المفيد من التأثير العاطفي غير العادل.",
  "Smooth, paints vivid emotional narratives for the jury, plays heavily to victim sympathy.": "يستخدم روايات عاطفية وأقوالاً منقولة. اختبر السماع وميّز الدليل المفيد من التأثير العاطفي غير العادل.",
  "Mansour thrives on storytelling. To keep his narrative flowing, he frequently skirts hearsay prohibitions under Rule 802, disguising second-hand gossip and rumors as mere background context or excited utterances. He uses expressive rhetoric to distract from gaps in physical proof.": "يستخدم روايات عاطفية وأقوالاً منقولة. اختبر السماع وميّز الدليل المفيد من التأثير العاطفي غير العادل.",
  "Disrupt his storytelling rhythm with swift objections under Rule 802 (Hearsay) and Rule 403 (Unfair Prejudice). If you let him speak uninterrupted, the jury will buy into his emotional narrative regardless of physical evidence gaps.": "اختبر السماع وميّز الدليل المفيد من التأثير العاطفي غير العادل.",
  "Charismatic Storyteller": "يستخدم روايات عاطفية وأقوالاً منقولة.",
  "Skirts around hearsay rules (FRE 802) by framing rumors as excited utterances or context.": "يستخدم روايات عاطفية وأقوالاً منقولة.",
  "A cold, unyielding trial attorney who specializes in breaking defendant alibis and securing cooperating witness testimony.": "تختبر روايات الغياب بالسجلات وتستخدم شهوداً متعاونين. تحقق من خط موكلك الزمني واطلب اتفاقات الشهود ووعودهم.",
  "Dispassionate, unyielding, zeroes in on defendant timeline contradictions without mercy.": "تختبر روايات الغياب بالسجلات وتستخدم شهوداً متعاونين. تحقق من خط موكلك الزمني واطلب اتفاقات الشهود ووعودهم.",
  "Rostova is dispassionate and laser-focused. She cuts plea bargains with informants and accomplices to isolate the primary defendant, then cross-checks client timeline statements against hard phone telemetry without showing any emotion.": "تختبر روايات الغياب بالسجلات وتستخدم شهوداً متعاونين. تحقق من خط موكلك الزمني واطلب اتفاقات الشهود ووعودهم.",
  "Subpoena every cooperating agreement and leniency deal her witnesses received under Brady disclosures. Show the jury what her star witnesses were promised in exchange for their testimony, and never let your client lock into an unverified timeline.": "تحقق من خط موكلك الزمني واطلب اتفاقات الشهود ووعودهم.",
  "Cold Realist / Deal-Cutter": "تختبر روايات الغياب بالسجلات وتستخدم شهوداً متعاونين.",
  "Uses cooperating witnesses and plea deals; attacks defendant alibis with cross-checks.": "تختبر روايات الغياب بالسجلات وتستخدم شهوداً متعاونين.",
  "A conservative, institutional prosecutor who relies almost exclusively on police officer credibility and standard department arrest reports.": "يعتمد على تقارير الشرطة والإجراءات المعتادة بحذر. قارن التقرير بالصوت الأصلي والدليل المادي وقدّم طلباً محدداً عند الجمع غير القانوني.",
  "Cautious, conservative with motions, over-indexes on police officer statements.": "يعتمد على تقارير الشرطة والإجراءات المعتادة بحذر. قارن التقرير بالصوت الأصلي والدليل المادي وقدّم طلباً محدداً عند الجمع غير القانوني.",
  "Delaney follows standard operating procedure to the letter. Because he relies so heavily on what the investigating detectives tell him, he is slow to adapt when unexpected physical contradictions emerge or when police reports conflict with actual dispatch audio.": "يعتمد على تقارير الشرطة والإجراءات المعتادة بحذر. قارن التقرير بالصوت الأصلي والدليل المادي وقدّم طلباً محدداً عند الجمع غير القانوني.",
  "Attack the foundation of police exhibits early with Fourth Amendment suppression motions. Delaney's entire trial strategy crumbles when key physical exhibits or warrantless search items are excluded from evidence.": "قارن التقرير بالصوت الأصلي والدليل المادي وقدّم طلباً محدداً عند الجمع غير القانوني.",
  "Bureaucratic / By-the-Book": "يعتمد على تقارير الشرطة والإجراءات المعتادة بحذر.",
  "Struggles when confronted with unexpected physical contradictions or suppressed exhibits.": "يعتمد على تقارير الشرطة والإجراءات المعتادة بحذر.",
  "A sharp, quick-tongued prosecutor known for rapid-fire cross-examinations designed to rattle nervous witnesses and induce slip-ups.": "تطرح أسئلة سريعة ومركبة ذات افتراضات متنازع عليها. اطلب سؤالاً واقعياً واحداً كل مرة وفق القاعدة 611(a).",
  "Sharp, sharp-tongued, fires quick compound questions to induce nervous slip-ups.": "تطرح أسئلة سريعة ومركبة ذات افتراضات متنازع عليها. اطلب سؤالاً واقعياً واحداً كل مرة وفق القاعدة 611(a).",
  "Zhang fires rapid compound questions, frequently assuming facts not yet entered into evidence to corner witnesses into affirmative answers before they have time to think. She constantly tests judicial limits to see how far the bench will let her push.": "تطرح أسئلة سريعة ومركبة ذات افتراضات متنازع عليها. اطلب سؤالاً واقعياً واحداً كل مرة وفق القاعدة 611(a).",
  "Interrupt her cadence immediately with Rule 611(a) (Compound Question / Assumes Facts Not in Evidence). Forcing her to break her questions down gives your witness room to breathe and exposes the unproven assumptions in her theory.": "اطلب سؤالاً واقعياً واحداً كل مرة وفق القاعدة 611(a).",
  "Rapid-Fire Cross-Examiner": "تطرح أسئلة سريعة ومركبة ذات افتراضات متنازع عليها.",
  "Frequently tests judicial boundaries with argumentative questions and assumed unproven facts.": "تطرح أسئلة سريعة ومركبة ذات افتراضات متنازع عليها.",
  "Violent Crimes": "جرائم العنف",
  "Financial Fraud & White-Collar Crimes": "الاحتيال المالي",
  "Cybercrime & Digital Intrusion": "الجرائم الرقمية",
  "Substance Use, Trafficking & Controlled Substances": "المخدرات والمواد المراقبة",
  "Overcharge Scenarios & Manslaughter": "المبالغة في التهم والقتل بظروف مخففة",
  "Type": "النوع",
  "Facts": "الوقائع",
  "Details": "التفاصيل",
  "Description": "الوصف",
  "Foundation": "أساس قبول الدليل [Foundation]",
  "Condition": "الحالة",
  "Date": "التاريخ",
  "Police": "ضابط شرطة",
  "civilian": "مدني",
  "police": "ضابط شرطة",
  "expert": "خبير",
  "Free": "مجاني",
  "State v. Unknown": "الادعاء ضد متهم غير محدد",
  "No truth specified.": "لم تُسجّل حقيقة أصلية لهذه القضية.",
  "Choose Arabic or English.": "اختر العربية أو الإنجليزية.",
  "[Sealed case record withheld]": "[الحقيقة الأصلية للقضية محجوبة]",
  "[Sealed record withheld]": "[السجل السري محجوب]"
};
